import type { EquipmentPart, EquipmentPMOperation, EquipmentMaintenanceRecord, PMPlanFull, EquipmentCalibration } from './store';

// تجهیزات اضافی از فرم‌های شناسنامه (تصاویر ارسالی)
export const EXTRA_EQUIPMENT_FROM_FORMS = [
  {
    name: 'دستگاه برش B3CUT4-1', feCode: 'B3CUT4-1', pmCode: 'B3CUT4-1', model: '-', serialNumber: '-',
    manufacturer: 'برتگال', country: 'چین', manufactureYear: '-', location: 'سالن برش', nodeType: 'machine',
    notes: 'نحوه کارکرد: هوای فشرده از کمپرسور به داخل بلوک برش فرستاده شده و پس از عمل برش هوای فشرده قطع شده و دستگاه به صورت دستی خاموش می‌شود. بلوک برش به طرفین و پایین حرکت می‌کند.',
    pmOperations: [
      { description: 'بازدید و بادگیری فیلترهای هوا', period: 'ماهانه' },
      { description: 'تعویض روغن دستگاه', period: 'ماهانه' },
      { description: 'بازدید و چک کردن گریس گیربکس', period: '۳ ماهه (فصلی)' },
      { description: 'بازدید گریس گیربکس', period: 'ماهانه' },
      { description: 'سرویس کردن و تمیز کردن محل ورودی دوز برش', period: 'ماهانه' },
      { description: 'چک کردن و تعویض فیلتر هوای کمپرسورها', period: 'ماهانه' },
      { description: 'بازدید روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'تعویض روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'گریس پمپ گیربکس', period: 'ماهانه' },
      { description: 'بازدید و تعویض تسمه موتور', period: '۳ ماهه (فصلی)' },
    ],
    parts: [
      { name: 'الکتروموتور ۵۴۵۸۱', criticality: 'main' },
      { name: 'گیربکس ۵۴۲۶۰۴', criticality: 'main' },
      { name: 'صفحه متحرک ۵۴۰۴۶', criticality: 'main' },
      { name: 'تیغه ساکن ۵۲۰۷۲۸', criticality: 'main' },
      { name: 'سیستم ساکشن ۵۴۳۵۸۶', criticality: 'main' },
      { name: 'الکتروموتور ۲۸۰-۱۰-kW ۵۴۲۵۸۶', criticality: 'main' },
      { name: 'سیستم کنترل (کنترل پنل) ۵۰۲۹۹۷', criticality: 'main' },
      { name: 'تیغه ساکن B-61, 520871', criticality: 'main' },
      { name: 'موتور تیزکننده تیغه ۱۸۰-۱۸kW', criticality: 'main' },
      { name: 'الکتروموتور ۱۴۵۰-۱۰-kW دور ۵۴۲۸۹', criticality: 'main' },
      { name: 'الکتروموتور ۵۴۳۵۸۶-۱۸۰-KW ۲۸۰۰-rpm', criticality: 'main' },
      { name: 'تیغ برش ۵۰۴۳۹۵-۹۲۸۰', criticality: 'main' },
      { name: 'مک هوا ۹-۴۸A', criticality: 'consumable' },
    ],
  },
  {
    name: 'درام', feCode: 'DRAM-01', pmCode: 'DRAM-01', model: 'D&N', serialNumber: 'no:۳۳۰۱۵۹۲۱-۴',
    manufacturer: 'D&N', country: 'ایران', manufactureYear: '-', location: 'تولید تاسیسات',
    notes: 'مدیر تولید: پرسیل تاسیسات. نحوه کار: درام را وصل نموده، دکمه استارت را می‌زنیم و دستگاه رطوبت موجود در هوای کمپرسور را می‌گیرد.',
    pmOperations: [
      { description: 'بازدید و بادگیری فیلترهای هوا', period: 'ماهانه' },
      { description: 'بازدید گیربکس دستگاه', period: 'روزانه' },
      { description: 'تعویض روغن گیربکس', period: 'ماهانه' },
      { description: 'بازدید دانه های گیر', period: 'ماهانه' },
      { description: 'چک کردن تابلو برق - ۵۰-گریز', period: 'سالانه' },
      { description: 'تعویض میکرو فیلترها', period: 'سالانه' },
    ],
    parts: [
      { name: 'ستیربوش دیافراگمی ۱/۲ اینچ', criticality: 'main' },
      { name: 'فیلترهای سیکلونی', criticality: 'main' },
      { name: 'تابلوبرق', criticality: 'main' },
      { name: 'سرورهای تخلیه برقی', criticality: 'secondary' },
      { name: '...carbon', criticality: 'consumable' },
    ],
    records: [
      { partName: 'valve1', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'valve2', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'پورت ۳', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'پورت ۴', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'لله گرها', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'سیگنال ۲', maintenanceDate: '2024-12-25', activityType: 'pm', pmOrEm: 'EM' },
      { partName: 'شیر اطمینان ۲', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'شیر اطمینان ۱', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'لله گره های هوا', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'نظافت' },
      { partName: 'میکرو فیلترهای درام', maintenanceDate: '2024-07-20', activityType: 'pm', pmOrEm: 'PM', description: 'تعویض' },
      { partName: 'شیر اطمینان', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
      { partName: 'پورتر سوئیچ', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
      { partName: 'پورتر روغن', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تعویض روغن' },
      { partName: 'فیلترها', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'نظافت' },
      { partName: 'پورترها', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'بازرسی' },
      { partName: 'سنسور ها', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'بازرسی' },
      { partName: 'سنسور تخلیه', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'بازرسی' },
      { partName: 'شیر تغذیه', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
      { partName: 'سیگنال', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
      { partName: 'شیر چک', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
      { partName: 'شیر دو', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
      { partName: 'لله آب گرها', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
      { partName: 'میکروفیلترها', maintenanceDate: '2024-12-16', activityType: 'cm', description: 'تست و مراتب سازی' },
    ],
  },
  {
    name: 'دیزل ژنراتور', feCode: 'GEN-01', pmCode: 'GEN-01', model: 'FCTAA8 کاتپیلر ۲۰-۴-۲۵-KVA', serialNumber: '-',
    manufacturer: 'کاتپیلر', country: 'انگلیس', manufactureYear: '1972', location: 'کارخانه فوم',
    capacity: '۲۰-۴۰۰V', power: '۲۰-۴۰KW',
    notes: 'ابتدا مقدار آب رادیاتور، روغن موتور، وضعیت ظاهری (نشتی، ...) کنترل گردد. سپس کلید سنکرون روی رولر و دکمه استارت را می‌زنیم. بعد از چند ثانیه دیزل راه اندازی می‌شود. کنترل می‌کنیم که سیستم دارای عملکرد مناسب باشد. باید دقت شود در حالت ON و پس از چند دقیقه بر روی ولتاژ تنظیم و سیست را بر روی مدار می‌آوریم. U.H. در حد از کار خروجی ۲۰۰-KW-۱۰۰-KW.',
    pmOperations: [
      { description: 'ثبت ساعت کارکرد دیزل', period: 'هفتگی' },
      { description: 'شارژ گازوئیل هر ۳ روز کاری', period: 'هفتگی' },
      { description: 'تعویض روغن دیزل ۱۵۰-h', period: 'ماهانه' },
      { description: 'تعویض فیلتر روغن ۱۵۰-h', period: 'سالانه' },
      { description: 'تعویض فیلتر گازوئیل ۱۲۰-h', period: 'سالانه' },
      { description: 'کنترل تسمه های دینام', period: '۳ ماهه (فصلی)' },
      { description: 'گریس خورها', period: '۳ ماهه (فصلی)' },
      { description: 'بازدید اتصالات', period: 'سالانه' },
      { description: 'چک کردن تابلو', period: '۳ ماهه (فصلی)' },
      { description: 'تمیز مشعله و شبکه آرمیچر', period: '۳ ماهه (فصلی)' },
      { description: 'تخلیه اب داخل مخزن گازوئیل', period: '۳ هفتگی' },
    ],
    parts: [
      { name: 'الکترومیزل ۶ سیلندر', criticality: 'main' },
      { name: 'مخزن سوخت', criticality: 'main' },
      { name: 'دینام شارژ باتری', criticality: 'main' },
      { name: 'رگولاتور KW ۳۵۰', criticality: 'main' },
      { name: 'تسمه پروانه AX 49', criticality: 'consumable' },
      { name: 'تسمه دینام AX44', criticality: 'consumable' },
      { name: 'تسمه اصلی پمپ N.5 ۳۱۷۶۲۸-', criticality: 'consumable' },
      { name: 'باتری ۱۵۰-۷ ۹۲۷', criticality: 'main' },
      { name: 'شارژر باتری ثابت ۲۹۷۰-۱۰-۸', criticality: 'main' },
      { name: 'رادیات آب ۴۰-L', criticality: 'main' },
      { name: 'مخزن روغن ۲۲L', criticality: 'main' },
      { name: 'فیلتر هوا', criticality: 'consumable' },
      { name: 'فیلتر روغن KLF747', criticality: 'consumable' },
      { name: 'فیلتر گازوئیل KFF185', criticality: 'consumable' },
      { name: 'گریس گیرها', criticality: 'consumable' },
    ],
  },
  {
    name: 'ربات تزریق ۱', feCode: 'ROBOT-01', pmCode: 'ROBOT-01', model: 'GMFanon Robotics S-430F', serialNumber: '-',
    manufacturer: 'جنرال موتورز فانون', country: 'آمریکا', manufactureYear: '1394', location: 'سالن تولید فوم',
    capacity: '۳۰۰ تن',
    notes: 'نحوه تولید به قالب با قالب قالب با یک دستگاه تزریق و سیستم ریزی و پیشگیری عملی می‌کند و با روشی به قالب ها تزریق می‌شود.',
    pmOperations: [
      { description: 'کنترل اتصالات های برقی و سیم‌های دستگاه', period: 'ماهانه' },
      { description: 'بازدید و بادگیری', period: 'ماهانه' },
      { description: 'کنترل سیم پیچ موتور کمپرسور', period: 'ماهانه' },
      { description: 'کنترل و تمیز کردن هواها', period: 'هفتگی' },
      { description: 'کنترل میزان باد دستگاه کمپرسور', period: 'ماهانه' },
      { description: 'بازدید و تمیز کردن تسمه های محرک', period: 'هفتگی' },
      { description: 'تعویض روغن هیدرولیکی', period: 'ماهانه' },
      { description: 'بازدید و کنترل فیلتر هوای موتور', period: 'هفتگی' },
      { description: 'تعویض فیلتر هوا', period: 'هفتگی' },
      { description: 'کنترل و تمیز کردن کابل برق', period: 'ماهانه' },
      { description: 'کنترل و تعویض فیلتر روغن', period: 'ماهانه' },
    ],
    parts: [
      { name: 'الکترودهای هوا', criticality: 'main' },
      { name: 'هد غراب', criticality: 'main' },
      { name: 'سیستم هیدرولیک', criticality: 'main' },
      { name: 'سیستم هیدرولیک (سیلندر)', criticality: 'main' },
      { name: 'سیستم هیدرولیک (پمپ)', criticality: 'main' },
      { name: 'موتور هوا', criticality: 'main' },
      { name: 'سیستم هیدرولیک', criticality: 'main' },
      { name: 'سیستم هیدرولیک', criticality: 'main' },
      { name: 'پمپ هیدرولیک', criticality: 'main' },
      { name: 'سیستم هیدرولیک (شیلنگ)', criticality: 'main' },
      { name: 'سیستم هیدرولیک', criticality: 'main' },
    ],
  },
  {
    name: 'دستگاه تزریق B1P02', feCode: 'B1P02', pmCode: 'B1P02', model: 'MA81C 1B/134/113B', serialNumber: 'T-250 (kg) / 715 - 650 (g/s)',
    manufacturer: 'مدیر تولید', country: 'تایوان/چین', manufactureYear: '1396', location: 'سالن تزریق',
    capacity: 'T-250 (kg)',
    notes: 'ابتدا قالب را باز کرده به دستگاه وصل می‌کنیم. قالب را بسته و دستگاه را به مدت ۸ ساعت گرم کرده، جهت تزریق در قالب ها.',
    pmOperations: [
      { description: 'کنترل سیستم هیدرولیک', period: 'روزانه' },
      { description: 'بازدید و بادگیری سیستم هوا', period: 'روزانه' },
      { description: 'کنترل شیر برقی', period: 'روزانه' },
      { description: 'کنترل پاور یونیت', period: 'روزانه' },
      { description: 'کنترل سیم پیچ ها', period: 'روزانه' },
      { description: 'تمیز کردن دستگاه', period: 'روزانه' },
      { description: 'کنترل سیستم هیدرولیک', period: 'روزانه' },
      { description: 'کنترل سیستم هیدرولیک', period: 'روزانه' },
      { description: 'کنترل قالب', period: 'روزانه' },
      { description: 'کنترل شیر برقی', period: 'روزانه' },
      { description: 'کنترل شیر برقی', period: 'روزانه' },
      { description: 'بازدید و کنترل شیر برقی', period: 'روزانه' },
      { description: 'کنترل شیر برقی', period: 'روزانه' },
      { description: 'کنترل و تعویض فیلتر روغن', period: 'ماهانه' },
      { description: 'کنترل شیر برقی', period: 'ماهانه' },
      { description: 'تعویض فیلتر هوا', period: 'ماهانه' },
      { description: 'بازرسی قالب', period: 'ماهانه' },
      { description: 'تعویض و شارژ روغن هیدرولیک', period: 'ماهانه' },
      { description: 'تعویض فیلتر روغن', period: 'ماهانه' },
      { description: 'تعویض و شارژ روغن هیدرولیک', period: 'ماهانه' },
      { description: 'کنترل سیستم هیدرولیک', period: 'ماهانه' },
      { description: 'بازرسی و تمیزکاری سیستم', period: 'ماهانه' },
      { description: 'کنترل و تعویض فیلتر روغن', period: 'ماهانه' },
    ],
    parts: [
      { name: 'پاور یونیت', criticality: 'main' },
      { name: 'سیستم هیدرولیک', criticality: 'main' },
      { name: 'موتور هیدرولیک', criticality: 'main' },
      { name: 'سیلندر هیدرولیک', criticality: 'main' },
      { name: 'قالب', criticality: 'main' },
      { name: 'سیستم کنترل', criticality: 'main' },
      { name: 'سنسور فشار', criticality: 'main' },
      { name: 'سنسور دما', criticality: 'main' },
      { name: 'سیستم خنک‌کننده', criticality: 'main' },
      { name: 'Mass Flow Meter', criticality: 'main' },
      { name: 'سیستم کنترل (PLC)', criticality: 'main' },
      { name: 'کنتاکتور', criticality: 'main' },
      { name: 'رله', criticality: 'secondary' },
      { name: 'شیلنگ فشار', criticality: 'consumable' },
    ],
  },
  {
    name: 'مخزن واکنشی B1P03-1', feCode: 'B1P03-1', pmCode: 'B1P03-1', model: '-', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'آلمان', manufactureYear: '1392/05/20', location: 'واحد فوم',
    capacity: '۱ تن',
    notes: 'واکنش فوم در مخزن با نازل واکنش پلی ال تامین می‌شود. A. درجه اهمیت تجهیز: A',
    pmOperations: [
      { description: 'کنترل نشتی', period: 'روزانه' },
      { description: 'بازدید فیلترها و تعویض آن در صورت نیاز', period: 'روزانه' },
      { description: 'بازدید روغن گیربکس پمپ', period: 'ماهانه' },
      { description: 'چک کردن تخته کلمب الکتروگیربکس', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض کلمه ضد پمپ', period: 'ماهانه' },
      { description: 'تعویض روغن گیربکس', period: 'ماهانه' },
      { description: 'کنترل گیربکس و فرمودگی شیلنگ', period: '۶ ماهه' },
      { description: 'تعویض روغن گیربکس پمپ', period: 'سالانه' },
    ],
    parts: [
      { name: 'الکترو موتور ۱۵ کیلو وات', criticality: 'main' },
      { name: 'الکترو پمپ دنده‌ای ۸۴۰ (خارج از فولاد ۲۲ کیلو وات به همراه گیربکس ۱ به ۵ زنجیره‌ای)', criticality: 'main' },
      { name: 'مخزن واکنش ۱ تن', criticality: 'main' },
      { name: 'سیستم تزریق و اتصالات', criticality: 'main' },
      { name: 'تابلو برق', criticality: 'main' },
      { name: 'الکتروموتور ۲ KW پمپ ۹۲۰ رگلاتور', criticality: 'main' },
      { name: 'LS موتور ۲۲KW', criticality: 'main' },
    ],
    records: [
      { partName: 'شیلنگ بارگیری', maintenanceDate: '2024-07-03', activityType: 'cm', description: 'تعویض پرس شیلنگ' },
      { partName: 'شیلنگ سیرکوله', maintenanceDate: '2024-07-03', activityType: 'cm', description: 'تعویض شیر اتصالات شیر کولر' },
      { partName: 'گیربکس پمپ بارگیری', maintenanceDate: '2024-11-30', activityType: 'pm', pmOrEm: 'PM', description: 'تعویض روغن گیربکس ۸۵W-' },
      { partName: 'پورت الکترو ۴۰۰ لیتری', maintenanceDate: '2024-10-20', activityType: 'cm', description: 'پرس پمپ جدید و اصلاح اتصالات - قراردهی پمپ' },
      { partName: 'کنتاکتور پلی', maintenanceDate: '2024-10-20', activityType: 'cm', description: 'نصب ابیور ۲۲ KW ال اس پمپ جدید' },
      { partName: 'تابلو برق چالو', maintenanceDate: '2024-10-20', activityType: 'cm', description: 'اصلاح تابلو (تغییر کلید حرارتی برای الکتروپمپ)' },
    ],
  },
  {
    name: 'دستگاه برش B3CUT1', feCode: 'B3CUT1', pmCode: 'B3CUT1', model: '-', serialNumber: '-',
    manufacturer: 'برتگال', country: 'چین', manufactureYear: '-', location: 'سالن برش',
    notes: 'نحوه کار: هوای فشرده از کمپرسور به داخل بلوک برش فرستاده شده و پس از عمل برش هوای فشرده قطع شده و دستگاه به صورت دستی خاموش می‌شود.',
    pmOperations: [
      { description: 'کنترل بلوک برش', period: 'روزانه' },
      { description: 'کنترل گیربکس', period: 'روزانه' },
      { description: 'بازدید موتور', period: 'روزانه' },
      { description: 'کنترل تابلو برق', period: 'روزانه' },
      { description: 'کنترل گیربکس', period: 'روزانه' },
      { description: 'کنترل موتور', period: 'روزانه' },
      { description: 'کنترل تابلو برق', period: 'روزانه' },
      { description: 'کنترل گیربکس', period: 'روزانه' },
      { description: 'کنترل موتور', period: 'روزانه' },
      { description: 'کنترل تابلو برق', period: 'روزانه' },
      { description: 'تعویض روغن گیربکس', period: 'ماهانه' },
      { description: 'بازدید و تعویض فیلتر هوا', period: 'ماهانه' },
    ],
    parts: [
      { name: 'موتور', criticality: 'main' },
      { name: 'گیربکس', criticality: 'main' },
      { name: 'بلوک برش', criticality: 'main' },
      { name: 'تیغه برش', criticality: 'main' },
      { name: 'تابلو برق', criticality: 'main' },
      { name: 'سیستم کنترل', criticality: 'main' },
    ],
  },
  {
    name: 'دستگاه برش B3CUT3', feCode: 'B3CUT3', pmCode: 'B3CUT3', model: '-', serialNumber: '-',
    manufacturer: 'برتگال', country: 'ایران', manufactureYear: '-', location: 'سالن برش',
    notes: 'نحوه کار: هوای فشرده از کمپرسور به داخل بلوک برش فرستاده شده و پس از عمل برش هوای فشرده قطع شده و دستگاه به صورت دستی خاموش می‌شود.',
    pmOperations: [
      { description: 'بازدید روغن گیربکس', period: 'ماهانه' },
      { description: 'بازدید و سرویس گراول و پینون محور عمودی', period: 'ماهانه' },
      { description: 'گریس کاری و روغن کاری چک ها', period: '۳ ماهه (فصلی)' },
      { description: 'بازدید سنگ های تیز کننده تیغه', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض روغن گیربکس', period: 'سالانه' },
      { description: 'بازدید و تعویض فیلتر هوای کمپرسور', period: 'ماهانه' },
      { description: 'بازدید روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'تعویض روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'گریس پمپ گیربکس', period: 'ماهانه' },
      { description: 'بازدید و تعویض تسمه موتور', period: '۳ ماهه (فصلی)' },
    ],
    parts: [
      { name: 'صفحه ی دوز ۵۰۲۹۹۷', criticality: 'main' },
      { name: 'تیغه ۵۴۱۲۵۲ کد ۴۸۵۳-۵۱۰-۹۰', criticality: 'main' },
      { name: 'چک ها ۵۴۱۷۳۴', criticality: 'main' },
      { name: 'گیربکس ۵۴۵۹۸', criticality: 'main' },
      { name: 'سیستم کنترل ۵۰۲۹۹۷', criticality: 'main' },
      { name: 'الکتروموتور ۱۴۵۰-RPM ۱۴۰-kW ۵۴۲۵۸۵', criticality: 'main' },
      { name: 'الکتروموتور ۱۴۵۰-RPM دو عدد ک', criticality: 'main' },
      { name: 'تیز کننده تیغه ۵۴۵۸۰', criticality: 'main' },
      { name: 'کوبلینگ هیدرولیک ۵۰۱۲۶۲', criticality: 'main' },
    ],
  },
  {
    name: 'لیفتراک کمپرسور هوا BT04', feCode: 'BT04', pmCode: 'BT04', model: '8FA25-35009', serialNumber: '-',
    manufacturer: 'راننده لیفتراک', country: 'ژاپن', manufactureYear: '2014', location: 'راننده لیفتراک',
    capacity: '۲. تن',
    notes: 'کنترل چک لیست روزانه. کنترل دستگاه در هنگام خاموش کردن. ۱- بستن کامل کلید ۲- قراردادن لیفتراک در محل تعیین شده ۳- خاموش بودن چراغ ها ۴- اطمینان از بسته بودن شیر کپسول گاز',
    pmOperations: [
      { description: 'بازدید روغن گیربکس', period: 'روزانه' },
      { description: 'بازدید روغن هیدرولیک', period: 'روزانه' },
      { description: 'بازدید روغن موتور', period: 'روزانه' },
      { description: 'بازدید باد لاستیک با گیج vbar', period: 'روزانه' },
      { description: 'بازدید آب رادیاتور (مخزن کوچک)', period: 'روزانه' },
      { description: 'بازدید روغن باطری', period: 'روزانه' },
      { description: 'بادگیری فیلتر هوا', period: 'هفتگی' },
      { description: 'بازدید و استرگاری نسخ و وایر', period: 'ماهانه' },
      { description: 'گریس کاری غلطک گریس خور', period: '۳ ماهه (فصلی)' },
      { description: 'نظافت و روغن کاری کلیه دکل و زنجیر', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض روغن موتور، فیلتر هوا، فیلتر روغن', period: '120-h' },
      { description: 'تعویض روغن گیربکس اتومات', period: '1000-h' },
      { description: 'تعویض فیلتر بالایی و پره‌ای گیربکس', period: '600-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '200-h' },
      { description: 'تعویض فیلتر روغن هیدرولیک', period: '1200-h' },
      { description: 'تعویض شمع و وایر', period: '1000-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '1200-h' },
    ],
    parts: [
      { name: 'موتور', criticality: 'main' },
      { name: 'گیربکس و دیفرانسیل', criticality: 'main' },
      { name: 'دکل', criticality: 'main' },
      { name: 'غلتک پاشنی', criticality: 'main' },
      { name: 'سیستم خنک کننده', criticality: 'main' },
      { name: 'باطری', criticality: 'main' },
      { name: 'شمع و وایر', criticality: 'consumable' },
      { name: 'رگلاتور گاز LPG', criticality: 'main' },
      { name: 'پمپ هیدرولیک', criticality: 'main' },
      { name: 'چرخ ها', criticality: 'main' },
      { name: 'پارکنگ دکل', criticality: 'main' },
      { name: 'پمپ های اهرم لیور', criticality: 'main' },
      { name: 'سیستم گاز LPG', criticality: 'main' },
      { name: 'BT7 سیم های', criticality: 'main' },
    ],
  },
  {
    name: 'لیفتراک H102', feCode: 'H102', pmCode: 'H102', model: 'FG30-17319799', serialNumber: '-',
    manufacturer: 'راننده لیفتراک', country: 'ژاپن', manufactureYear: '2014', location: 'راننده لیفتراک',
    capacity: '۳ تن',
    notes: 'دارای عدل گیر. کنترل چک لیست روزانه. کنترل دستگاه در هنگام خاموش کردن. ۱- بستن کامل کلید ۲- قراردادن لیفتراک در محل تعیین شده ۳- خاموش بودن چراغ ها ۴- اطمینان از بسته بودن شیر کپسول گاز',
    pmOperations: [
      { description: 'بازدید روغن گیربکس', period: 'روزانه' },
      { description: 'بازدید روغن هیدرولیک', period: 'روزانه' },
      { description: 'بازدید روغن موتور', period: 'روزانه' },
      { description: 'بازدید باد لاستیک با گیج vbar', period: 'روزانه' },
      { description: 'بازدید آب رادیاتور (مخزن کوچک)', period: 'روزانه' },
      { description: 'بازدید روغن باطری', period: 'روزانه' },
      { description: 'بادگیری فیلتر هوا', period: 'هفتگی' },
      { description: 'بازدید و استرگاری نسخ و وایر', period: 'ماهانه' },
      { description: 'گریس کاری غلطک گریس خور', period: '۳ ماهه (فصلی)' },
      { description: 'نظافت و روغن کاری کلیه دکل و زنجیر', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض روغن موتور، فیلتر هوا، فیلتر روغن', period: '120-h' },
      { description: 'تعویض روغن گیربکس اتومات', period: '1000-h' },
      { description: 'تعویض فیلتر بالایی و پره‌ای گیربکس', period: '600-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '200-h' },
      { description: 'تعویض فیلتر روغن هیدرولیک', period: '1200-h' },
      { description: 'تعویض شمع و وایر', period: '1000-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '1200-h' },
    ],
    parts: [
      { name: 'موتور', criticality: 'main' },
      { name: 'گیربکس و دیفرانسیل', criticality: 'main' },
      { name: 'دکل', criticality: 'main' },
      { name: 'غلتک پاشنی', criticality: 'main' },
      { name: 'سیستم خنک کننده', criticality: 'main' },
      { name: 'باطری', criticality: 'main' },
      { name: 'شمع و وایر', criticality: 'consumable' },
      { name: 'رگلاتور گاز LPG', criticality: 'main' },
      { name: 'پمپ هیدرولیک', criticality: 'main' },
      { name: 'چرخ ها', criticality: 'main' },
      { name: 'پارکنگ دکل', criticality: 'main' },
      { name: 'پمپ های اهرم لیور', criticality: 'main' },
      { name: 'سیستم گاز LPG', criticality: 'main' },
      { name: 'BT7 سیم های', criticality: 'main' },
    ],
  },
  {
    name: 'چیلر', feCode: 'CHILLER-01', pmCode: 'CHILLER-01', model: 'کمپرسور سریال ۴۵۷۵-۱۰-۹', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'آمریکا', manufactureYear: '-', location: 'تولید تاسیسات',
    capacity: '۱۰ تنی',
    notes: 'سرپرس تولید: مسول تعمیر و نگهداری. آب مخزن چیلر چک شود، فشار گاز چک شود، شیر آب باز شود و بعد از بررسی استارت شود، جهت گردش هوا و پمپ و دیاپا و روغن هیدرولیک.',
    pmOperations: [
      { description: 'اسید گرفتن', period: 'روزانه' },
      { description: 'کنترل عملکرد فن ها', period: 'روزانه' },
      { description: 'کنترل عملکرد ترموستات', period: 'روزانه' },
      { description: 'کنترل آب مخزن', period: 'روزانه' },
      { description: 'کنترل عملکرد پمپ آب', period: 'روزانه' },
      { description: 'کنترل عملکرد کمپرسور', period: 'روزانه' },
      { description: 'کنترل عملکرد فن تابلو برق', period: 'روزانه' },
      { description: 'کنترل عملکرد سوخت و ولو', period: 'روزانه' },
      { description: 'کنترل عملکرد ترموکوپل', period: 'روزانه' },
      { description: 'نظافت کندانسور', period: 'ماهانه' },
      { description: 'شارژ گاز چیلر', period: 'ماهانه' },
      { description: 'کنترل روغن کمپرسور', period: 'بر حسب نیاز' },
    ],
    parts: [
      { name: 'گیج کمپرسور', criticality: 'main' },
      { name: 'گیج گاز کمپرسور', criticality: 'main' },
      { name: 'مخزن آب', criticality: 'main' },
      { name: 'پمپ آب', criticality: 'main' },
      { name: 'شیر آب', criticality: 'main' },
      { name: 'فن ها', criticality: 'main' },
      { name: 'کمپرسور', criticality: 'main' },
      { name: 'پمپ آب', criticality: 'main' },
      { name: 'تراب', criticality: 'main' },
      { name: 'ترموکوپل', criticality: 'main' },
      { name: 'کندانسور (…)', criticality: 'main' },
      { name: 'سرویس دما', criticality: 'main' },
      { name: 'فن مکانیک دما', criticality: 'main' },
      { name: 'سرویس گازی (سوخت و ولو)', criticality: 'main' },
    ],
    records: [
      { partName: 'شارژ گاز چیلر', maintenanceDate: '2024-02-25', activityType: 'cm' },
      { partName: 'نشتی گاز', maintenanceDate: '2024-06-30', activityType: 'cm' },
      { partName: 'شارژ گاز چیلر', maintenanceDate: '2024-07-17', activityType: 'cm' },
      { partName: 'شارژ گاز چیلر', maintenanceDate: '2024-09-09', activityType: 'cm' },
      { partName: 'نشتی گاز', maintenanceDate: '2024-09-09', activityType: 'cm' },
      { partName: 'ضد یخ', maintenanceDate: '2024-12-12', activityType: 'cm' },
      { partName: 'پوسیدگی برقی', maintenanceDate: '2024-11-25', activityType: 'cm', description: 'تعویض' },
      { partName: 'مخزن بویلول', maintenanceDate: '2024-02-27', activityType: 'cm', description: 'رفع و تعویض مسیر ورودی' },
    ],
  },
  {
    name: 'جت پرینتر', feCode: 'JET-01', pmCode: 'JET-01', model: 'Hitachi INK Jet printer RX-S UXRX', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'ژاپن', manufactureYear: '-', location: 'خط پرینتر',
    notes: 'مشخصات تولید (تاریخ و زمان تولید) روی محصول توسط این دستگاه چاپ می‌شود.',
    pmOperations: [
      { description: 'بادگیری و تمیز کردن تابلو برق', period: 'ماهانه' },
      { description: 'بادگیری و تمیز کردن هد پرینتر', period: 'ماهانه' },
    ],
    parts: [
      { name: 'تابلو برق', criticality: 'main' },
      { name: 'هد پرینتر', criticality: 'main' },
    ],
    records: [
      { partName: 'تابلو برق', maintenanceDate: '2024-07-18', activityType: 'cm' },
      { partName: 'شمعشوی مسیر', maintenanceDate: '2024-07-18', activityType: 'cm' },
      { partName: 'شمع برق', maintenanceDate: '2024-07-18', activityType: 'cm' },
      { partName: 'هد', maintenanceDate: '2024-07-18', activityType: 'cm' },
      { partName: 'تابلو برق', maintenanceDate: '2024-07-18', activityType: 'cm' },
      { partName: 'هد', maintenanceDate: '2024-07-18', activityType: 'cm', pmOrEm: 'EM' },
      { partName: 'تراز', maintenanceDate: '2024-12-27', activityType: 'cm', description: 'نظافت' },
    ],
  },
  {
    name: 'هات پلیت MR HEI-TEC', feCode: 'SC-123', pmCode: 'SC-123', model: 'MR HEI-TEC hot plate', serialNumber: '-',
    manufacturer: 'آلمان', country: 'آلمان', manufactureYear: '-', location: 'آزمایشگاه',
    notes: 'دستگاه ثبت خاصیت ارتجاعی',
    calibration: {
      range: 'محدوده دمایی: ۳۰-۳۰۰ درجه / محدوده گشتاور همزن مغناطیسی: RPM ۱۴۰۰۰',
      parameter: 'دما و RPM',
      accuracy: '-',
      period: 'یک ساله',
      type: 'external',
      location: 'آزمایشگاه',
      method: 'The Calibration was carried out according to: IDS 1361',
      records: [
        { date: '2024-01-16', calibratorName: 'کالیبراسیون کالکو' },
        { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
      ],
    },
    pmOperations: [],
    parts: [],
  },
  {
    name: 'دستگاه برش B3CUT4', feCode: 'B3CUT4', pmCode: 'B3CUT4', model: '-', serialNumber: '-',
    manufacturer: 'برتگال', country: 'تایوان', manufactureYear: '-', location: 'سالن برش',
    notes: 'پس از وصل نمودن برق اصلی دستگاه از تابلو برق و فشار دادن کلید سبز ON، دستگاه روشن و بلوک ها بصورت عمودی برش داده می‌شوند.',
    pmOperations: [
      { description: 'بازدید تسمه A-42', period: 'ماهانه' },
      { description: 'بازدید روغن گیربکس', period: 'ماهانه' },
      { description: 'بازدید روغن سیندر هوا', period: 'ماهانه' },
      { description: 'بازدید سرویس گراول و پینون محور عمودی', period: 'ماهانه' },
      { description: 'گریس کاری و روغن کاری صفحه دوار', period: '۳ ماهه (فصلی)' },
      { description: 'بازدید سنگ های تیز کننده تیغه', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض روغن گیربکس', period: 'ماهانه' },
      { description: 'بادگیری و تعویض فیلتر هوای کمپرسورها', period: 'ماهانه' },
      { description: 'بازدید روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'تعویض روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'گریس پمپ گیربکس', period: 'ماهانه' },
      { description: 'بازدید و تعویض تسمه پیستون', period: '۳ ماهه (فصلی)' },
    ],
    parts: [
      { name: 'الکتروموتور ۲۸۰-rpm ۲۸-kw کد ۵۴۵۸۷', criticality: 'main' },
      { name: 'تسمه برش ۴۸۵۳-۵۱۰-۹۰ ایتنی کد ۵۰۴۳۹۵', criticality: 'main' },
      { name: 'الکتروموتور ۱۸۰-۱۸kW ۵hp کد ۵۴۵۸۵', criticality: 'main' },
      { name: 'تسمه ۵۴۰۴۲۸ A-42 (کمبریوسر)', criticality: 'consumable' },
      { name: 'الکتروموتور (گیربکس) ۲۸۰۰-rpm کد ۵۰۲۸۷', criticality: 'main' },
      { name: 'صفحه دوار ۵۰۲۹۶', criticality: 'main' },
      { name: 'چک های بالابر ۵۴۱۶۳۴', criticality: 'main' },
      { name: 'گیربکس ۵۴۶۰', criticality: 'main' },
      { name: 'میکروسوئیچ ۵۰۴۰۶۹', criticality: 'main' },
      { name: 'سیستم کنترل ۵۰۲۹۹۷', criticality: 'main' },
      { name: 'الکتروموتور تیزکننده تیغه ۱۲۰-kW', criticality: 'main' },
      { name: 'مخزن کمپرسور هوا', criticality: 'main' },
      { name: 'کمپرسور ۲۵۰-اتلیتری تکنز ۴HP', criticality: 'main' },
      { name: 'شیلنگ پنوماتیک ۱۰ کی ۵۰۱۲۶۲', criticality: 'main' },
    ],
  },
  {
    name: 'ربات تزریق ۲ B1P4', feCode: 'B1P4', pmCode: 'B1P4', model: 'FANUC Robotics S-420F', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'آمریکا', manufactureYear: '-', location: 'سالن تولید فوم',
    notes: 'مواد اولیه در نازل این ربات با هم مخلوط و به داخل قالب ها تزریق می‌شود.',
    pmOperations: [
      { description: 'کنترل شیلنگ های تزریق و هیدرولیک', period: 'روزانه' },
      { description: 'کنترل سرورهای کنترل کمپرسور', period: 'روزانه' },
      { description: 'کنترل وایرینگ', period: 'روزانه' },
      { description: 'کنترل نشتی و کنترل فشارهای کلی', period: 'روزانه' },
      { description: 'گریس کاری قطعات متحرک موتور محرک', period: '۳ ماهه' },
      { description: 'روغن کاری غلطک گریس خور', period: '۳ ماهه' },
      { description: 'بادگیری و نظافت تابلوهای برق', period: '۳ ماهه' },
      { description: 'اجزاگشتی پایه ها و قطعات متحرک تجهیز', period: 'سالانه' },
    ],
    parts: [
      { name: 'تابلوهای برق', criticality: 'main' },
      { name: 'هد تزریق', criticality: 'main' },
      { name: 'شیلنگ های هیدرولیک و مواد', criticality: 'main' },
      { name: 'چرخ های هیدره شک', criticality: 'main' },
    ],
    records: [
      { partName: 'شیلنگ هیدرولیک', maintenanceDate: '2024-04-30', activityType: 'cm', pmOrEm: 'EM' },
      { partName: 'هد تزریق', maintenanceDate: '2024-08-29', activityType: 'cm', pmOrEm: 'EM' },
      { partName: 'هد تزریق', maintenanceDate: '2024-08-29', activityType: 'cm', pmOrEm: 'EM' },
      { partName: 'هیدرولیک', maintenanceDate: '2024-08-29', activityType: 'cm', pmOrEm: 'EM' },
      { partName: 'نازل', maintenanceDate: '2024-09-12', activityType: 'cm', pmOrEm: 'EM' },
      { partName: 'شنگها و گریس خورها', maintenanceDate: '2024-12-25', activityType: 'pm', pmOrEm: 'PM', description: 'روانکاری مفاتل متحرک (شنگها) و گریس خورها' },
      { partName: 'سروموتور', maintenanceDate: '2024-11-25', activityType: 'cm', pmOrEm: 'EM' },
      { partName: 'سروموتورها', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'سنسورها', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'بادگیری' },
      { partName: 'سوکت‌ها', maintenanceDate: '2024-11-28', activityType: 'cm', pmOrEm: 'PM', description: 'تعویض' },
      { partName: 'سیمت‌ها', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'مرتب سازی' },
      { partName: 'شیر هیدرولیکی', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'تعویض' },
      { partName: 'شیلنگ هیدرولیک', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'تعویض پرس' },
      { partName: 'سیرکولرها', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'تعویض پرس' },
      { partName: 'سیرکولرها', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'تعویض فرسودگی' },
      { partName: 'تابلو برق', maintenanceDate: '2024-07-30', activityType: 'cm', description: 'اجراگشتی و بادگیری' },
      { partName: 'وایرینگ‌ها', maintenanceDate: '2024-08-15', activityType: 'cm', description: 'کنترل وایرینگ ها' },
    ],
  },
  {
    name: 'کلاوم شب دار انتقال فوم B1PPR-5', feCode: 'B1PPR-5', pmCode: 'B1PPR-5', model: '۱۲۲CM', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'ایران', manufactureYear: '-', location: 'سالن تولید فوم',
    notes: 'عرض تسمه نوار نقاله ۱۲۲CM - طول نوار نقاله... جنس نوار نقاله... نوار نقاله ۳ تکه میباشد. از کلاوم شب دار انتقال فوم به انبار پلاس.',
    pmOperations: [
      { description: 'تعویض روغن گیربکس', period: '۳ ماهه (فصلی)' },
      { description: 'بازدید و گریس کاری غلط گریس خور (باطلای)', period: 'ماهانه' },
      { description: 'بازدید و نظافت و روغن کاری رولیک ها', period: 'ماهانه' },
      { description: 'چک کردن نشتا متحرک و پایه های نگهدارنده', period: 'ماهانه' },
      { description: 'چک کردن تابلوهای برق و کلیدهای کنتاکتور', period: '۳ ماهه (فصلی)' },
      { description: 'چک کردن نخشه کلم الکتروموتورها و پایه های موتور', period: '۳ ماهه (فصلی)' },
      { description: 'کنترل عملکرد کلیدهای اضطراری (الکترونیکی)', period: 'ماهانه' },
      { description: 'در صورت وجود ترک با شکاف سریعاً رفع گردد (ایراد)', period: 'روزانه' },
      { description: 'بازگان نوار نقاله و نوار پایه ها', period: 'ماهانه' },
    ],
    parts: [
      { name: 'الکترو گیربکس ۲۳KW-۱۴۳۰-RPM (دنده)', criticality: 'main' },
      { name: 'گیربکس (رضایت موتور و موتوژن)', criticality: 'main' },
      { name: 'رولیک‌ها', criticality: 'main' },
      { name: 'باطلای', criticality: 'main' },
      { name: 'پایه‌های نگهدارنده', criticality: 'main' },
      { name: 'نوار نقاله', criticality: 'consumable' },
      { name: 'درام‌ها', criticality: 'main' },
    ],
  },
  {
    name: 'کلاوم دسر ۳ B1PPR-3', feCode: 'B1PPR-3', pmCode: 'B1PPR-3', model: '۳ متر', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'ایران', manufactureYear: '-', location: 'سالن تولید فوم',
    notes: 'عرض تسمه نوار نقاله CM-5 طول نوار نقاله ۵M جنس نوار نقاله PVC. از کلاوم دسر ۳.',
    pmOperations: [
      { description: 'کنترل نوار نقاله جهت عدم وجود ترک و شکاف', period: 'روزانه' },
      { description: 'بازدید تابلو برق و اتصال منه کنتاکتور و کلیدها', period: 'ماهانه' },
      { description: 'بازگشت نوار نقاله و نوار پایه ها', period: 'ماهانه' },
      { description: 'بازدید و گریس کاری غلط گریس خور (باطلای)', period: 'ماهانه' },
      { description: 'بازدید و نظافت و روغن کاری رولیک ها', period: 'ماهانه' },
      { description: 'چک کردن نشتا متحرک و پایه های نگهدارنده', period: 'ماهانه' },
      { description: 'چک کردن تابلوهای برق و کلیدهای کنتاکتور', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض روغن گیربکس', period: '۳ ماهه (فصلی)' },
      { description: 'چک کردن نخشه کلم الکتروموتورها و پایه های موتور', period: '۳ ماهه (فصلی)' },
    ],
    parts: [
      { name: 'الکتروگیربکس ۱۳۰۰-RPM ۵KW', criticality: 'main' },
      { name: 'گیربکس ایتالیا', criticality: 'main' },
      { name: 'باطلای', criticality: 'main' },
      { name: 'نوار نقاله ۶۰ (Cme15M)', criticality: 'consumable' },
      { name: 'درام', criticality: 'main' },
      { name: 'تحمیر و چرخ دنده باطلای', criticality: 'main' },
    ],
    records: [
      { partName: 'تابلو برق', maintenanceDate: '2024-12-16', activityType: 'cm', pmOrEm: 'EM', description: 'اجزا گشتی' },
      { partName: 'پولی DRIVE', maintenanceDate: '2024-12-16', activityType: 'cm', pmOrEm: 'EM', description: 'نظافت و بازرسی' },
      { partName: 'پولی هرزگرد', maintenanceDate: '2024-12-16', activityType: 'cm', pmOrEm: 'EM', description: 'نظافت و بازرسی' },
      { partName: 'رولر', maintenanceDate: '2024-12-27', activityType: 'cm', pmOrEm: 'EM', description: 'نظافت و بازرسی' },
      { partName: 'الکتروموتور', maintenanceDate: '2024-12-27', activityType: 'cm', pmOrEm: 'EM', description: 'اجزا گشتی و نظافت' },
      { partName: 'گیربکس', maintenanceDate: '2024-12-27', activityType: 'cm', pmOrEm: 'EM', description: 'نظافت و بازرسی' },
      { partName: 'سیم کشی', maintenanceDate: '2024-12-27', activityType: 'cm', pmOrEm: 'EM', description: 'مرتب سازی' },
      { partName: 'تسمه', maintenanceDate: '2024-12-27', activityType: 'cm', pmOrEm: 'EM', description: 'سیسماله زدن' },
    ],
  },
  {
    name: 'ساندریجوز ۲X', feCode: 'SAND-2X', pmCode: 'SAND-2X', model: '-', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'ایران', manufactureYear: '-', location: 'سالن تولید فوم',
    capacity: 'KW ۲/۲',
    notes: 'پرسنل تولید: مدیر تولید',
    pmOperations: [],
    parts: [
      { name: 'الکتروموتور KW ۲/۲', criticality: 'main' },
      { name: 'تابلوهای برق', criticality: 'main' },
      { name: 'کابل های نمونه', criticality: 'consumable' },
    ],
  },
  {
    name: 'لیفتراک تویوتا BT03', feCode: 'BT03', pmCode: 'BT03', model: '2-8fg25R625-3501', serialNumber: '-',
    manufacturer: 'راننده لیفتراک', country: 'ژاپن', manufactureYear: '2014', location: 'راننده لیفتراک',
    capacity: '۳ تن',
    notes: 'دارای عدل گیر. کنترل چک لیست روزانه.',
    pmOperations: [
      { description: 'بازدید روغن گیربکس', period: 'روزانه' },
      { description: 'بازدید روغن هیدرولیک', period: 'روزانه' },
      { description: 'بازدید روغن موتور', period: 'روزانه' },
      { description: 'بازدید باد لاستیک با گیج vbar', period: 'روزانه' },
      { description: 'بازدید آب رادیاتور (مخزن کوچک)', period: 'روزانه' },
      { description: 'بازدید روغن باطری', period: 'روزانه' },
      { description: 'بادگیری فیلتر هوا', period: 'هفتگی' },
      { description: 'بازدید و استرگاری نسخ و وایر', period: 'ماهانه' },
      { description: 'گریس کاری غلطک گریس خور', period: '۳ ماهه (فصلی)' },
      { description: 'نظافت و روغن کاری کلیه دکل و زنجیر', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض روغن موتور، فیلتر هوا، فیلتر روغن', period: '120-h' },
      { description: 'تعویض روغن گیربکس اتومات', period: '1000-h' },
      { description: 'تعویض فیلتر بالایی و پره‌ای گیربکس', period: '600-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '200-h' },
      { description: 'تعویض فیلتر روغن هیدرولیک', period: '1200-h' },
      { description: 'تعویض شمع و وایر', period: '1000-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '1200-h' },
    ],
    parts: [
      { name: 'موتور', criticality: 'main' },
      { name: 'گیربکس و دیفرانسیل', criticality: 'main' },
      { name: 'دکل', criticality: 'main' },
      { name: 'غلتک پاشنی', criticality: 'main' },
      { name: 'سیستم خنک کننده', criticality: 'main' },
      { name: 'باطری', criticality: 'main' },
      { name: 'شمع و وایر', criticality: 'consumable' },
      { name: 'رگلاتور گاز LPG', criticality: 'main' },
      { name: 'پمپ هیدرولیک', criticality: 'main' },
      { name: 'چرخ ها', criticality: 'main' },
      { name: 'پارکنگ دکل', criticality: 'main' },
      { name: 'پمپ های اهرم لیور', criticality: 'main' },
      { name: 'سیستم گاز LPG', criticality: 'main' },
      { name: 'BT7 سیم های', criticality: 'main' },
    ],
  },
  {
    name: 'درب پانل خیابان ۴ GD10', feCode: 'GD10', pmCode: 'GD10', model: 'GD10', serialNumber: '-',
    manufacturer: 'نگهبان', country: 'ایران', manufactureYear: '1402', location: 'محوطه نگهداری کارخانه فوم',
    notes: 'درام RV5 (چین)، الکتروموتور INVTGD10 ۰.۷۵KW. هر دستگاه نیاز به نگه‌داشتن دائمه بصورت درب باز و بسته می‌گردد.',
    pmOperations: [
      { description: 'نظافت پروسه الکتروموتور (بوسیله بلور)', period: '۳ هفته' },
      { description: 'چک کردن نخشه کلم و پایه کلمی الکتروگیربکس', period: '۳ ماهه (فصلی)' },
      { description: 'روغن کاری و نظافت شفت گیربکس', period: 'ماهانه' },
      { description: 'گریس کاری چرخ دنده شفت ای و ریل شفت ای', period: 'ماهانه' },
      { description: 'روغن کاری و نظافت غلطک های درب', period: 'ماهانه' },
      { description: 'چک کردن شفت باطلو برق', period: '۳ ماهه (فصلی)' },
      { description: 'کنترل چشمی باز از لحاظ عملکرد و STOP', period: 'هفتگی' },
      { description: 'بازدید و تعویض روغن گیربکس', period: '۶ ماهه' },
    ],
    parts: [
      { name: 'الکتروموتور زیمنس ۰.۷۵KW', criticality: 'main' },
      { name: 'گیربکس', criticality: 'main' },
      { name: 'درایو INVT مدل ۱۰ INVT GD ۰.۷KW GD', criticality: 'main' },
      { name: 'ریل شفت دنده ای ۱۰۰-۸ متر', criticality: 'main' },
      { name: 'خرچ دنده شفت ای ۱ عدد', criticality: 'main' },
      { name: 'میکروسوئیچ ۲۰-dB+XLX8', criticality: 'main' },
      { name: 'چشمی درب (اضطراری)', criticality: 'main' },
    ],
  },
  {
    name: 'دیگ بخار', feCode: 'BOILER-01', pmCode: 'BOILER-01', model: 'UDGL 25-3', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'ایران', manufactureYear: '-', location: 'تولید تاسیسات',
    capacity: 'فشار ۱-۰Bar - ۱۸۲',
    notes: 'ابتدا پمپ آب را روشن کرده مسیر آب به دیگ را باز می‌کنیم. همزمان مسیر گاز را باز کرده و مشعل را روشن می‌کنیم. بعد از ۱۲ ساعت کار، مشعل خاموش شده و دیگ سرد می‌شود.',
    pmOperations: [
      { description: 'کنترل صحت کارکرد گیج ها', period: 'روزانه' },
      { description: 'کنترل صحت آب گزی و آلارم', period: 'روزانه' },
      { description: 'کنترل مقدار آب مخزن', period: 'روزانه' },
      { description: 'کنترل عملکرد دمپر', period: 'روزانه' },
      { description: 'کنترل پمپ گازوئیل', period: 'روزانه' },
      { description: 'کنترل پمپ آب', period: 'روزانه' },
      { description: 'کنترل ترموستات', period: 'روزانه' },
      { description: 'کنترل شیر کاری', period: 'روزانه' },
      { description: 'کنترل عملکرد چشمی UV', period: 'ماهانه' },
    ],
    parts: [
      { name: 'چشمی UV', criticality: 'main' },
      { name: 'gas valve', criticality: 'main' },
      { name: 'شیر گاز', criticality: 'main' },
      { name: 'پمپ گازوئیل', criticality: 'main' },
      { name: 'پمپ آب', criticality: 'main' },
      { name: 'گیج', criticality: 'main' },
      { name: 'ترموکوپل', criticality: 'main' },
      { name: 'PT100', criticality: 'main' },
      { name: 'تابلو برق', criticality: 'main' },
    ],
    records: [
      { partName: 'چشمی UV', maintenanceDate: '2024-02-18', activityType: 'cm' },
      { partName: 'تابلو برق', maintenanceDate: '2024-06-02', activityType: 'cm' },
      { partName: 'مشعل گازوئیل', maintenanceDate: '2024-06-02', activityType: 'cm', description: 'تست' },
      { partName: 'شیربرقی گاز', maintenanceDate: '2024-06-02', activityType: 'cm' },
      { partName: 'پمپ آب', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'تست' },
      { partName: '-', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'تست گازوئیل' },
      { partName: 'نحوه هوا', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'چشمی مشعل', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'دریچه هوای مشعل', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'شیر گاز', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'فشار گاز', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'فشار سنج استاتیک', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'تشت بندها', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'لوا ایزواگ ترموستات', maintenanceDate: '2024-04-12', activityType: 'cm' },
      { partName: 'ساخت تابلو برق فرمان', maintenanceDate: '2024-04-28', activityType: 'cm' },
      { partName: 'منظم کردن تابلو برق', maintenanceDate: '2024-05-24', activityType: 'cm' },
    ],
  },
  {
    name: 'کمپرسور عمودی Fimi', feCode: 'COMP-FIMI', pmCode: 'COMP-FIMI', model: '86-L/M', serialNumber: '2911974-021',
    manufacturer: 'مدیر تولید', country: 'ایتالیا', manufactureYear: '-', location: 'تولید تاسیسات',
    notes: 'بعد از بررسی نکات ایمنی، کلیدهای سرور مربوطه به ترتیب بسته می‌شوند. با فشردن فشار گاز ۸-۰ Bar جهت مصرف تولید و ساعت استارت می‌شود.',
    pmOperations: [
      { description: 'کنترل صحت عملکرد pressur switch', period: 'روزانه' },
      { description: 'کنترل صحت کمپرسور', period: 'روزانه' },
      { description: 'کنترل دمای کمپرسور', period: 'روزانه' },
      { description: 'کنترل گیج', period: 'هفتگی' },
      { description: 'تعویض روغن', period: '۳ ماهه (فصلی)' },
      { description: 'کنترل صحت عملکرد سوپاپ اطمینان', period: '۳ ماهه (فصلی)' },
      { description: 'کنترل شیره‌های تخلیه مخزن و مخزن گیرها', period: '۳ ماهه (فصلی)' },
      { description: 'اجزاگشتی و بادگیری تابلو برق', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض تسمه', period: 'سالانه' },
      { description: 'بازدید و بادگیری فیلتر هوا', period: 'ماهانه' },
      { description: 'بازدید تسمه', period: 'ماهانه' },
    ],
    parts: [
      { name: 'گیج', criticality: 'main' },
      { name: 'pressur switch', criticality: 'main' },
      { name: 'کمپرسور', criticality: 'main' },
      { name: 'تابلو برق', criticality: 'main' },
      { name: 'مخزن گیر', criticality: 'main' },
      { name: 'سیر کلوله', criticality: 'main' },
      { name: 'سوپاپ اطمینان', criticality: 'main' },
      { name: 'تابلو برق', criticality: 'main' },
      { name: 'سیر تخلیه مخزن', criticality: 'main' },
    ],
    records: [
      { partName: 'تسمه', maintenanceDate: '2024-06-02', activityType: 'cm' },
      { partName: 'روغن', maintenanceDate: '2024-06-02', activityType: 'cm', pmOrEm: 'PM' },
      { partName: 'دریچه‌ها', maintenanceDate: '2024-06-02', activityType: 'cm' },
      { partName: 'تعویض روغن', maintenanceDate: '2024-06-24', activityType: 'cm' },
      { partName: 'پورتر سوئیچ', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'روغن', maintenanceDate: '2024-12-25', activityType: 'cm', pmOrEm: 'PM' },
      { partName: 'شیر اطمینان', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'شیر تخلیه', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'شیره‌های پنوماتیکی', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'شیلنگ - کلمه', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'سیر گیرها', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'فیلتر هوا', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'نظافت دستگاه', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'سیلندر', maintenanceDate: '2024-09-25', activityType: 'cm', description: 'تعویض سیلندر' },
    ],
  },
  {
    name: 'درب ریلی خیابان ۶', feCode: 'GATE-06', pmCode: 'GATE-06', model: 'NICE', serialNumber: '-',
    manufacturer: 'نگهبان', country: '-', manufactureYear: '-', location: 'محوطه ورودی خیابان ۶',
    notes: 'دارای کلید خلاص. در هنگام باز و بسته کردن درب با دکمه بصورت درب باز و بسته می‌گردد.',
    pmOperations: [
      { description: 'نظافت پروسه و قاب پوله الکتروموتور', period: '۳ هفته' },
      { description: 'چک کردن نخشه کلم و پایه های الکتروگیربکس', period: '۳ ماهه (فصلی)' },
      { description: 'روغن کاری و نظافت شفت گیربکس', period: 'ماهانه' },
      { description: 'گریس کاری چرخ دنده شفت ای و ریل شفت ای', period: 'ماهانه' },
      { description: 'روغن کاری و نظافت غلطک های درب', period: 'ماهانه' },
      { description: 'چک کردن شفت تابلو برق', period: '۳ ماهه (فصلی)' },
      { description: 'کنترل چشمی باز از لحاظ عملکرد START-STOP', period: 'هفتگی' },
      { description: 'بازدید و تعویض روغن گیربکس', period: '۶ ماهه' },
    ],
    parts: [
      { name: 'ریل و رست شفت ای', criticality: 'main' },
      { name: 'دنده شفت ای', criticality: 'main' },
      { name: 'ریل شفت ای', criticality: 'main' },
      { name: 'باطری', criticality: 'main' },
      { name: 'ریل و رست شفت', criticality: 'main' },
      { name: 'ریل و رست شفت', criticality: 'main' },
    ],
  },
  {
    name: 'لیفتراک بال BT05', feCode: 'BT05', pmCode: 'BT05', model: 'Bx10-N-1717', serialNumber: '-',
    manufacturer: 'راننده لیفتراک', country: 'آمریکا', manufactureYear: '-', location: 'مخزن اولیه تولید فوم',
    capacity: '۶ تن',
    notes: 'کنترل چک لیست روزانه. کنترل دستگاه در هنگام خاموش کردن. ۱- بستن کامل کلید ۲- قراردادن لیفتراک در محل تعیین شده ۳- خاموش بودن چراغ ها ۴- اطمینان از بسته بودن شیر کپسول گاز',
    pmOperations: [
      { description: 'بازدید روغن گیربکس', period: 'روزانه' },
      { description: 'بازدید روغن هیدرولیک', period: 'روزانه' },
      { description: 'بازدید روغن موتور', period: 'روزانه' },
      { description: 'بازدید باد لاستیک با گیج vbar', period: 'روزانه' },
      { description: 'بازدید آب رادیاتور (مخزن کوچک)', period: 'روزانه' },
      { description: 'بازدید روغن باطری', period: 'روزانه' },
      { description: 'بادگیری فیلتر هوا', period: 'هفتگی' },
      { description: 'بازدید و استرگاری نسخ و وایر', period: 'ماهانه' },
      { description: 'گریس کاری غلطک گریس خور', period: '۳ ماهه (فصلی)' },
      { description: 'نظافت و روغن کاری کلیه دکل و زنجیر', period: '۳ ماهه (فصلی)' },
      { description: 'تعویض روغن موتور، فیلتر هوا، فیلتر روغن', period: '120-h' },
      { description: 'تعویض روغن گیربکس اتومات', period: '1000-h' },
      { description: 'تعویض فیلتر بالایی و پره‌ای گیربکس', period: '600-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '200-h' },
      { description: 'تعویض فیلتر روغن هیدرولیک', period: '1200-h' },
      { description: 'تعویض شمع و وایر', period: '1000-h' },
      { description: 'تعویض فیلتر داخلی گیربکس', period: '1200-h' },
    ],
    parts: [
      { name: 'موتور', criticality: 'main' },
      { name: 'گیربکس و دیفرانسیل', criticality: 'main' },
      { name: 'دکل', criticality: 'main' },
      { name: 'غلتک با ناحی', criticality: 'main' },
      { name: 'سیستم خنک کننده', criticality: 'main' },
      { name: 'باطری', criticality: 'main' },
      { name: 'شمع و وایر', criticality: 'consumable' },
      { name: 'رگلاتور گاز LPG', criticality: 'main' },
      { name: 'پمپ هیدرولیک', criticality: 'main' },
      { name: 'چرخ ها', criticality: 'main' },
      { name: 'پارکنگ دکل', criticality: 'main' },
      { name: 'پمپ های اهرم لیور', criticality: 'main' },
      { name: 'سیستم گاز LPG', criticality: 'main' },
      { name: 'BT7 سیم های', criticality: 'main' },
    ],
  },
  {
    name: 'دستگاه برش B3CUT2', feCode: 'B3CUT2', pmCode: 'B3CUT2', model: '-', serialNumber: '-',
    manufacturer: 'برتگال', country: 'چین', manufactureYear: '-', location: 'سالن برش',
    notes: 'پس از وصل نمودن برق اصلی دستگاه از تابلو برق و فشار دادن کلید سبز ON، دستگاه روشن و بلوک ها بصورت عمودی برش داده می‌شوند.',
    pmOperations: [
      { description: 'گریس کاری الکتروموتور', period: 'ماهانه' },
      { description: 'بازدید تسمه های دستگاه', period: 'فصلی' },
      { description: 'روغن کاری گیربکس و باطلای', period: 'فصلی' },
      { description: 'سرویس گراول و پینون محور عمودی تیز برش', period: 'ماهانه' },
      { description: 'بادگیری و تعویض فیلتر هوای کمپرسورها', period: 'ماهانه' },
      { description: 'بازدید روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'تعویض روغن کمپرسور هوا', period: 'ماهانه' },
      { description: 'گریس پمپ گیربکس', period: 'ماهانه' },
      { description: 'بازدید و تعویض تسمه پیستون', period: '۳ ماهه (فصلی)' },
    ],
    parts: [
      { name: 'الکتروموتور ۲.۲KW (دودهنده) ۵۴۵۸۹', criticality: 'main' },
      { name: 'تیغه ۸.۴YM کد ۵۳۲۵۷۲', criticality: 'main' },
      { name: 'صفحه متحرک ۵۰۴۰۴۶', criticality: 'main' },
      { name: 'تیزها ۵۰۴۳۲۴ IR25 کد', criticality: 'main' },
      { name: 'تسمه ساپر ۵۴۰۱ کد ۵۴۵۷۲۲', criticality: 'main' },
      { name: 'بلنک هدایت تیغه', criticality: 'main' },
      { name: 'موتورهای تیز کننده تیغه', criticality: 'main' },
      { name: 'الکتروموتور KW, 1400RPM کد ۵۰۴۷۰۸', criticality: 'main' },
    ],
  },
  {
    name: 'کلاوم شب دار انتقال فوم B1PF8-4', feCode: 'B1PF8-4', pmCode: 'B1PF8-4', model: '۲۰ متر', serialNumber: '-',
    manufacturer: 'مدیر تولید', country: 'ایران', manufactureYear: '-', location: 'سالن تولید فوم',
    notes: 'عرض تسمه نوار نقاله ۱۰۰-CM - طول نوار نقاله ۲۰ متر - جنس نوار نقاله PVC. از کلاوم شب دار انتقال فوم به انبار فوم.',
    pmOperations: [
      { description: 'تعویض روغن گیربکس', period: '۳ ماهه (فصلی)' },
      { description: 'بازدید و گریس کاری غلط گریس خور (باطلای)', period: 'ماهانه' },
      { description: 'بازدید و نظافت و روغن کاری رولیک ها', period: 'ماهانه' },
      { description: 'چک کردن نشتا متحرک و پایه های نگهدارنده', period: 'ماهانه' },
      { description: 'چک کردن تابلوهای برق و کلیدهای کنتاکتور', period: '۳ ماهه (فصلی)' },
      { description: 'چک کردن نخشه کلم الکتروموتورها و پایه های موتور', period: '۳ ماهه (فصلی)' },
      { description: 'کنترل عملکرد کلیدهای اضطراری (الکترونیکی)', period: 'ماهانه' },
      { description: 'در صورت وجود ترک با شکاف سریعاً رفع گردد (ایراد)', period: 'روزانه' },
      { description: 'بازگان نوار نقاله و نوار پایه ها', period: 'ماهانه' },
    ],
    parts: [
      { name: 'الکترو گیربکس ۲.۲KW-۱۴۳۰-RPM', criticality: 'main' },
      { name: 'درام ۲ عدد', criticality: 'main' },
      { name: 'رولیک‌ها', criticality: 'main' },
      { name: 'پایه ها و پایه', criticality: 'main' },
      { name: 'باطلای', criticality: 'main' },
      { name: 'نوار نقاله ۱۰-M-100-CM', criticality: 'consumable' },
    ],
    records: [
      { partName: 'الکتروموتور', maintenanceDate: '2024-04-28', activityType: 'cm' },
      { partName: 'نظافت قطعات', maintenanceDate: '2024-04-28', activityType: 'cm', pmOrEm: 'PM', description: 'روغن کاری' },
      { partName: 'تسمه', maintenanceDate: '2024-05-29', activityType: 'cm' },
      { partName: 'نشت', maintenanceDate: '2024-08-24', activityType: 'cm', pmOrEm: 'PM', description: 'تعویض' },
    ],
  },
  {
    name: 'بالابر BT13', feCode: 'BT13', pmCode: 'BT13', model: 'PHDL1400', serialNumber: '-',
    manufacturer: 'شرکت پترو پالای پارس', country: 'ایران', manufactureYear: '1400', location: 'انبار ۶',
    capacity: '250KG',
    notes: 'عرض ۱۹۲cm - ارتفاع در حالت بسته ۳.۲۵cm - ارتفاع کابین ۱۴۰cm - ۱۴۰+ مخ دستگاه ۸۵-kg. بررسی سیستم‌های مکانیکی و الکتریکی.',
    pmOperations: [
      { description: 'بازرسی فیزیکی کلم های استوار و کنترل عملکرد صحیح آنها', period: 'در زمان استفاده' },
      { description: 'بازرسی میکرو سوئیچ‌ها و اطمینان از عملکرد صحیح آنها', period: 'در زمان استفاده' },
      { description: 'اطمینان از عملکرد صحیح فرمان قبل از یک کردن دستگاه', period: 'در زمان استفاده' },
      { description: 'چک کردن دورهای موتورهای فرمان و موتورهای آن ها', period: 'قبل از زمان استفاده' },
      { description: 'بازدید از قفل‌ها و زنجیرهای اتصال به ریل', period: 'هفتگی' },
      { description: 'بازدید کلم‌های استوار و روانکاری با گریس', period: 'ماهانه' },
      { description: 'بازدید زنجیرها و گریس کاری آنها', period: '۳ ماهه' },
      { description: 'تعویض روغن هیدرولیک', period: 'سالانه' },
      { description: 'در شرایط مناسب جوی و بازندگی و خاک در محل سر پیشینه نگهداری شود', period: '-' },
    ],
    parts: [
      { name: 'دینام موتوژن 1.5KW', criticality: 'main' },
      { name: 'باطری', criticality: 'main' },
      { name: 'چک ها (ناستیک پارس)', criticality: 'main' },
      { name: 'چک های پیچی حفظ تعادل', criticality: 'main' },
      { name: 'چک‌های بالا/برنده', criticality: 'main' },
      { name: 'تابلو برق ۲ فاز', criticality: 'main' },
      { name: 'مخزن روغن گیربکس', criticality: 'main' },
      { name: 'پمپ روغن', criticality: 'main' },
      { name: 'جرم ها و فرفره', criticality: 'main' },
    ],
  },
  {
    name: 'ربات واکنش B1P05', feCode: 'B1P05', pmCode: 'B1P05', model: '-', serialNumber: '-',
    manufacturer: 'مدیر کارخانه', country: 'آمریکا', manufactureYear: '-', location: 'سالن تولید فوم',
    notes: 'تجهیز به علت عدم نیاز به مصرف غیر فعال می‌باشد. پس از متصل قالب ها جهت تزریق مخلوط مواد می‌باشد.',
    pmOperations: [
      { description: 'چک کردن شیلنگ های تزریق', period: 'روزانه' },
      { description: 'نظافت عمومی دستگاه', period: 'روزانه' },
      { description: 'نظافت نازل ها', period: 'روزانه' },
      { description: 'کنترل پمپ و الکتروموتور', period: 'روزانه' },
      { description: 'سرویس وایرینگ ها', period: 'روزانه' },
      { description: 'کنترل مخزن و وایر و میکسرها', period: 'هفتگی' },
      { description: 'چک کردن و بادگیری تابلو برق', period: 'ماهانه' },
      { description: 'کنترل تمام سرویس های انجام شده توسط اپراتور', period: 'ماهانه' },
      { description: 'روغن کاری قطعات ریلی خور', period: 'ماهانه' },
      { description: 'گریس کاری محور ها', period: 'ماهانه/۳ ماهه' },
    ],
    parts: [
      { name: 'سرور موتور', criticality: 'main' },
      { name: 'سرودرایو', criticality: 'main' },
      { name: 'هد تزریق', criticality: 'main' },
      { name: 'ریل ها و چرخ های هیدرولیک', criticality: 'main' },
      { name: 'تابلو برق', criticality: 'main' },
    ],
    records: [
      { partName: 'پمپ', maintenanceDate: '2024-06-03', activityType: 'cm' },
      { partName: 'الکتروموتور', maintenanceDate: '2024-11-16', activityType: 'cm' },
      { partName: 'میکسر', maintenanceDate: '2024-11-16', activityType: 'cm' },
      { partName: 'گراست فن', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'الکترو موتور', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'تابلو برق', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'تمیز کاری', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'میکسرها', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'مخزن واکنش', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'عبارت حاشیه‌ای' },
      { partName: 'رولرها', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'چاله واکنش', maintenanceDate: '2024-12-25', activityType: 'cm', description: 'نظافت' },
      { partName: 'ریلهای', maintenanceDate: '2024-12-25', activityType: 'cm' },
      { partName: 'گیج مخزن واکنش', maintenanceDate: '2024-12-24', activityType: 'cm', description: 'تعویض روغن' },
      { partName: 'نازل', maintenanceDate: '2024-06-02', activityType: 'cm', description: 'نظافت' },
      { partName: 'تخلیه مواد', maintenanceDate: '2024-12-16', activityType: 'cm' },
      { partName: 'الکترو موتور', maintenanceDate: '2024-12-27', activityType: 'cm', description: 'اجزا گشتی و نظافت' },
      { partName: 'گیربکس', maintenanceDate: '2024-12-27', activityType: 'cm', description: 'اجزا گشتی و نظافت' },
      { partName: 'سیر بندی', maintenanceDate: '2024-12-27', activityType: 'cm', description: 'بازرسی و مرتب سازی' },
    ],
  },
];

// کالیبراسیون برای دستگاه‌های اندازه‌گیری
export const EXTRA_CALIBRATIONS: Record<string, any> = {
  'SC-119': {
    range: '-',
    parameter: 'نیرو (N)',
    accuracy: '-',
    period: 'یک ساله',
    type: 'external',
    location: 'آزمایشگاه',
    method: 'The calibration internal procedure NO: ISO 7500 - ASTM E4 - OIML R65',
    records: [
      { date: '2024-01-16', calibratorName: 'آزمایشگاه کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-120': {
    range: '۴۰ گرم',
    parameter: 'جرم',
    accuracy: '۰.۰۱ گرم',
    period: 'یک ساله',
    type: 'external',
    location: 'آزمایشگاه',
    method: 'RASAM internal procedure NO: R - IT - 028\nThe calibration was carried out according to: IDS 311- 314',
    records: [
      { date: '2024-01-16', calibratorName: 'آزمایشگاه کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-123': {
    range: 'محدوده دمایی: ۳۰-۳۰۰ درجه / محدوده گشتاور همزن مغناطیسی: RPM ۱۴۰۰۰',
    parameter: 'دما و RPM',
    accuracy: '-',
    period: 'یک ساله',
    type: 'external',
    location: 'آزمایشگاه',
    method: 'The Calibration was carried out according to: IDS 1361',
    records: [
      { date: '2024-01-16', calibratorName: 'کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-126': {
    range: '-۵۰ تا +۳۶۰ درجه سانتی گراد',
    parameter: 'دما',
    accuracy: '-',
    period: 'یک ساله',
    type: 'external',
    location: 'آزمایشگاه',
    method: '-',
    records: [
      { date: '2024-01-16', calibratorName: 'کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-125': {
    range: '۰ تا ۳۰۰ میلی‌متر',
    parameter: 'طول',
    accuracy: '-',
    period: 'یک ساله',
    type: 'internal',
    location: 'آزمایشگاه',
    method: '-',
    records: [
      { date: '2024-01-16', calibratorName: 'کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-122': {
    range: '-',
    parameter: 'دما',
    accuracy: '-',
    period: 'یک ساله',
    type: 'external',
    location: 'آزمایشگاه',
    method: 'The Calibration was carried out according to: IDS 1361',
    records: [
      { date: '2024-01-16', calibratorName: 'آزمایشگاه کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-117': {
    range: '-',
    parameter: 'دما',
    accuracy: '-',
    period: 'یک ساله',
    type: 'external',
    location: 'آزمایشگاه',
    method: '-',
    records: [
      { date: '2024-01-16', calibratorName: 'کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-127': {
    range: '-',
    parameter: 'عبور هوا',
    accuracy: '-',
    period: 'یک ساله',
    type: 'internal',
    location: 'آزمایشگاه',
    method: '-',
    records: [
      { date: '2024-01-16', calibratorName: 'کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
  'SC-128': {
    range: '-',
    parameter: 'عبور هوا',
    accuracy: '-',
    period: 'یک ساله',
    type: 'internal',
    location: 'آزمایشگاه',
    method: '-',
    records: [
      { date: '2024-01-16', calibratorName: 'کالیبراسیون کالکو' },
      { date: '2024-06-11', calibratorName: 'آزمایشگاه کالیبراسیون رسام' },
    ],
  },
};
